[package]
name = "rust_test"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.26.1"
comfy-table = "7.1.1"
crossterm = "0.28.1"
csv = "1.3.0"
prettytable-rs = "0.10.0"
ratatui = "0.28.1"
serde_json = "1.0"
