[package]
name = "tabler"
version = "0.1.0"
edition = "2021"

[dependencies]

calamine = "0.26.1"
clap = { version = "4.5.21", features = ["cargo"] }
colored = "2.2.0"
csv = "1.3.0"
prettytable-rs = "0.10.0"
relative-path = "1.9.3"
serde_json = { version = "1.0", features = ["preserve_order"] }
